weights: v5lite-e.pt
cfg: models/yolov5s-shufflenetv2.yaml
data: data/na.yaml
hyp: data/hyp.scratch.yaml
epochs: 300
batch_size: 16
img_size:
- 320
- 320
workers: 0
device: '0'
resume: false
nosave: false
notest: false
single_cls: false
rect: false
noautoanchor: true
evolve: false
multi_scale: false
label_smoothing: 0.0
adam: false
sync_bn: false
linear_lr: false
cache_images: false
image_weights: false
bucket: ''
project: runs/train
name: exp
exist_ok: false
quad: false
save_period: -1
artifact_alias: latest
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
save_dir: runs\train\exp
